spring:
  application:
    name: nfe-books
  datasource:
    url: jdbc:h2:file:${NFE_101_HOME}/data/books
    username: sa
    password: password
    driverClassName: org.h2.Driver
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      id.db_structure_naming_strategy: legacy
  sql:
    init:
      mode: always
  h2:
    console.enabled: true      

#http://localhost:8080/h2-console      
